declare module '*.css';
declare module '*.less';
declare module '*.json';
declare module '*.jpg';
declare module '*.jpge';
declare module '*.png';
declare module '*.gif';
declare module '*.svg';
declare module '*.bmp';
