export interface EmojiconType {
  unifiedCode: string;
  cnCode: string;
}

export interface EmojiconsArr {
  emoji: EmojiconType[];
  title: string;
}

// 表情
export const emojicons: EmojiconType[] = [
  { unifiedCode: 'U+1f600', cnCode: '😀' },
  { unifiedCode: 'U+1f601', cnCode: '😁' },
  { unifiedCode: 'U+1f602', cnCode: '😂' },
  { unifiedCode: 'U+1f923', cnCode: '🤣' },
  { unifiedCode: 'U+1f603', cnCode: '😃' },
  { unifiedCode: 'U+1f604', cnCode: '😄' },
  { unifiedCode: 'U+1f605', cnCode: '😅' },
  { unifiedCode: 'U+1f606', cnCode: '😆' },
  { unifiedCode: 'U+1f609', cnCode: '😉' },
  { unifiedCode: 'U+1f60a', cnCode: '😊' },
  { unifiedCode: 'U+1f60b', cnCode: '😋' },
  { unifiedCode: 'U+1f60e', cnCode: '😎' },
  { unifiedCode: 'U+1f60d', cnCode: '😍' },
  { unifiedCode: 'U+1f618', cnCode: '😘' },
  { unifiedCode: 'U+1f617', cnCode: '😗' },
  { unifiedCode: 'U+1f619', cnCode: '😙' },
  { unifiedCode: 'U+1f61a', cnCode: '😚' },
  // { unifiedCode:"U+263a", "cnCode": "☺" },
  { unifiedCode: 'U+1f642', cnCode: '🙂' },
  { unifiedCode: 'U+1f917', cnCode: '🤗' },
  { unifiedCode: 'U+1f914', cnCode: '🤔' },
  { unifiedCode: 'U+1f610', cnCode: '😐' },
  { unifiedCode: 'U+1f611', cnCode: '😑' },
  { unifiedCode: 'U+1f636', cnCode: '😶' },
  { unifiedCode: 'U+1f644', cnCode: '🙄' },
  { unifiedCode: 'U+1f60f', cnCode: '😏' },
  { unifiedCode: 'U+1f623', cnCode: '😣' },
  { unifiedCode: 'U+1f625', cnCode: '😥' },
  { unifiedCode: 'U+1f62e', cnCode: '😮' },
  { unifiedCode: 'U+1f910', cnCode: '🤐' },
  { unifiedCode: 'U+1f62f', cnCode: '😯' },
  { unifiedCode: 'U+1f62a', cnCode: '😪' },
  { unifiedCode: 'U+1f62b', cnCode: '😫' },
  { unifiedCode: 'U+1f634', cnCode: '😴' },
  { unifiedCode: 'U+1f60c', cnCode: '😌' },
  { unifiedCode: 'U+1f61b', cnCode: '😛' },
  { unifiedCode: 'U+1f61c', cnCode: '😜' },
  { unifiedCode: 'U+1f61d', cnCode: '😝' },
  { unifiedCode: 'U+1f924', cnCode: '🤤' },
  { unifiedCode: 'U+1f612', cnCode: '😒' },
  { unifiedCode: 'U+1f613', cnCode: '😓' },
  { unifiedCode: 'U+1f614', cnCode: '😔' },
  { unifiedCode: 'U+1f615', cnCode: '😕' },
  { unifiedCode: 'U+1f643', cnCode: '🙃' },
  { unifiedCode: 'U+1f911', cnCode: '🤑' },
  { unifiedCode: 'U+1f632', cnCode: '😲' },
  // { unifiedCode:"U+2639", "cnCode": "☹" },
  { unifiedCode: 'U+1f641', cnCode: '🙁' },
  { unifiedCode: 'U+1f616', cnCode: '😖' },
  { unifiedCode: 'U+1f61e', cnCode: '😞' },
  { unifiedCode: 'U+1f61f', cnCode: '😟' },
  { unifiedCode: 'U+1f624', cnCode: '😤' },
  { unifiedCode: 'U+1f622', cnCode: '😢' },
  { unifiedCode: 'U+1f62d', cnCode: '😭' },
  { unifiedCode: 'U+1f626', cnCode: '😦' },
  { unifiedCode: 'U+1f627', cnCode: '😧' },
  { unifiedCode: 'U+1f628', cnCode: '😨' },
  { unifiedCode: 'U+1f629', cnCode: '😩' },
  { unifiedCode: 'U+1f62c', cnCode: '😬' },
  { unifiedCode: 'U+1f630', cnCode: '😰' },
  { unifiedCode: 'U+1f631', cnCode: '😱' },
  { unifiedCode: 'U+1f633', cnCode: '😳' },
  { unifiedCode: 'U+1f635', cnCode: '😵' },
  { unifiedCode: 'U+1f621', cnCode: '😡' },
  { unifiedCode: 'U+1f620', cnCode: '😠' },
  { unifiedCode: 'U+1f637', cnCode: '😷' },
  { unifiedCode: 'U+1f912', cnCode: '🤒' },
  { unifiedCode: 'U+1f915', cnCode: '🤕' },
  { unifiedCode: 'U+1f922', cnCode: '🤢' },
  { unifiedCode: 'U+1f927', cnCode: '🤧' },
  { unifiedCode: 'U+1f607', cnCode: '😇' },
  { unifiedCode: 'U+1f920', cnCode: '🤠' },
  { unifiedCode: 'U+1f921', cnCode: '🤡' },
  { unifiedCode: 'U+1f925', cnCode: '🤥' },
  { unifiedCode: 'U+1f913', cnCode: '🤓' },
  { unifiedCode: 'U+1f608', cnCode: '😈' },
  { unifiedCode: 'U+1f47f', cnCode: '👿' },
  { unifiedCode: 'U+1f479', cnCode: '👹' },
  { unifiedCode: 'U+1f47a', cnCode: '👺' },
  { unifiedCode: 'U+1f480', cnCode: '💀' },
  { unifiedCode: 'U+1f47b', cnCode: '👻' },
  { unifiedCode: 'U+1f47d', cnCode: '👽' },
  { unifiedCode: 'U+1f916', cnCode: '🤖' },
  { unifiedCode: 'U+1f4a9', cnCode: '💩' },
  { unifiedCode: 'U+1f63a', cnCode: '😺' },
  { unifiedCode: 'U+1f638', cnCode: '😸' },
  { unifiedCode: 'U+1f639', cnCode: '😹' },
  { unifiedCode: 'U+1f63b', cnCode: '😻' },
  { unifiedCode: 'U+1f63c', cnCode: '😼' },
  { unifiedCode: 'U+1f63d', cnCode: '😽' },
  { unifiedCode: 'U+1f640', cnCode: '🙀' },
  { unifiedCode: 'U+1f63f', cnCode: '😿' },
  { unifiedCode: 'U+1f63e', cnCode: '😾' },
];
// 动物与自然
export const animalAndNativeEmoji: EmojiconType[] = [
  { unifiedCode: 'U+1f648', cnCode: '🙈' },
  { unifiedCode: 'U+1f649', cnCode: '🙉' },
  { unifiedCode: 'U+1f64a', cnCode: '🙊' },
  { unifiedCode: 'U+1f4a5', cnCode: '💥' },
  { unifiedCode: 'U+1f4a6', cnCode: '💦' },
  { unifiedCode: 'U+1f4a8', cnCode: '💨' },
  { unifiedCode: 'U+1f4ab', cnCode: '💫' },
  { unifiedCode: 'U+1f435', cnCode: '🐵' },
  { unifiedCode: 'U+1f412', cnCode: '🐒' },
  { unifiedCode: 'U+1f98d', cnCode: '🦍' },
  { unifiedCode: 'U+1f436', cnCode: '🐶' },
  { unifiedCode: 'U+1f415', cnCode: '🐕' },
  { unifiedCode: 'U+1f429', cnCode: '🐩' },
  { unifiedCode: 'U+1f43a', cnCode: '🐺' },
  { unifiedCode: 'U+1f98a', cnCode: '🦊' },
  { unifiedCode: 'U+1f431', cnCode: '🐱' },
  { unifiedCode: 'U+1f408', cnCode: '🐈' },
  { unifiedCode: 'U+1f981', cnCode: '🦁' },
  { unifiedCode: 'U+1f42f', cnCode: '🐯' },
  { unifiedCode: 'U+1f405', cnCode: '🐅' },
  { unifiedCode: 'U+1f406', cnCode: '🐆' },
  { unifiedCode: 'U+1f434', cnCode: '🐴' },
  { unifiedCode: 'U+1f40e', cnCode: '🐎' },
  { unifiedCode: 'U+1f984', cnCode: '🦄' },
  { unifiedCode: 'U+1f98c', cnCode: '🦌' },
  { unifiedCode: 'U+1f42e', cnCode: '🐮' },
  { unifiedCode: 'U+1f402', cnCode: '🐂' },
  { unifiedCode: 'U+1f403', cnCode: '🐃' },
  { unifiedCode: 'U+1f404', cnCode: '🐄' },
  { unifiedCode: 'U+1f437', cnCode: '🐷' },
  { unifiedCode: 'U+1f416', cnCode: '🐖' },
  { unifiedCode: 'U+1f417', cnCode: '🐗' },
  { unifiedCode: 'U+1f43d', cnCode: '🐽' },
  { unifiedCode: 'U+1f40f', cnCode: '🐏' },
  { unifiedCode: 'U+1f411', cnCode: '🐑' },
  { unifiedCode: 'U+1f410', cnCode: '🐐' },
  { unifiedCode: 'U+1f42a', cnCode: '🐪' },
  { unifiedCode: 'U+1f42b', cnCode: '🐫' },
  { unifiedCode: 'U+1f418', cnCode: '🐘' },
  { unifiedCode: 'U+1f98f', cnCode: '🦏' },
  { unifiedCode: 'U+1f42d', cnCode: '🐭' },
  { unifiedCode: 'U+1f401', cnCode: '🐁' },
  { unifiedCode: 'U+1f400', cnCode: '🐀' },
  { unifiedCode: 'U+1f439', cnCode: '🐹' },
  { unifiedCode: 'U+1f430', cnCode: '🐰' },
  { unifiedCode: 'U+1f407', cnCode: '🐇' },
  { unifiedCode: 'U+1f43f', cnCode: '🐿' },
  { unifiedCode: 'U+1f987', cnCode: '🦇' },
  { unifiedCode: 'U+1f43b', cnCode: '🐻' },
  { unifiedCode: 'U+1f428', cnCode: '🐨' },
  { unifiedCode: 'U+1f43c', cnCode: '🐼' },
  { unifiedCode: 'U+1f43e', cnCode: '🐾' },
  { unifiedCode: 'U+1f983', cnCode: '🦃' },
  { unifiedCode: 'U+1f433', cnCode: '🐳' },
  { unifiedCode: 'U+1f40b', cnCode: '🐋' },
  { unifiedCode: 'U+1f42c', cnCode: '🐬' },
  { unifiedCode: 'U+1f41f', cnCode: '🐟' },
  { unifiedCode: 'U+1f40c', cnCode: '🐌' },
  { unifiedCode: 'U+1f98b', cnCode: '🦋' },
  { unifiedCode: 'U+1f41b', cnCode: '🐛' },
  { unifiedCode: 'U+1f41c', cnCode: '🐜' },
  { unifiedCode: 'U+1f490', cnCode: '💐' },
  { unifiedCode: 'U+1f338', cnCode: '🌸' },
  { unifiedCode: 'U+1f339', cnCode: '🌹' },
  { unifiedCode: 'U+1f940', cnCode: '🥀' },
  { unifiedCode: 'U+1f331', cnCode: '🌱' },
  { unifiedCode: 'U+26c5', cnCode: '⛅' },
  { unifiedCode: 'U+26c8', cnCode: '⛈' },
  { unifiedCode: 'U+1f324', cnCode: '🌤' },
  { unifiedCode: 'U+1f325', cnCode: '🌥' },
  { unifiedCode: 'U+1f326', cnCode: '🌦' },
  { unifiedCode: 'U+1f327', cnCode: '🌧' },
  { unifiedCode: 'U+1f328', cnCode: '🌨' },
  { unifiedCode: 'U+1f329', cnCode: '🌩' },
];
// 美食与饮料
export const foodAndDrinkEmoji: EmojiconType[] = [
  { unifiedCode: 'U+1f347', cnCode: '🍇' },
  { unifiedCode: 'U+1f348', cnCode: '🍈' },
  { unifiedCode: 'U+1f349', cnCode: '🍉' },
  { unifiedCode: 'U+1f34a', cnCode: '🍊' },
  { unifiedCode: 'U+1f34b', cnCode: '🍋' },
  { unifiedCode: 'U+1f34c', cnCode: '🍌' },
  { unifiedCode: 'U+1f34d', cnCode: '🍍' },
  { unifiedCode: 'U+1f34e', cnCode: '🍎' },
  { unifiedCode: 'U+1f34f', cnCode: '🍏' },
  { unifiedCode: 'U+1f350', cnCode: '🍐' },
  { unifiedCode: 'U+1f351', cnCode: '🍑' },
  { unifiedCode: 'U+1f352', cnCode: '🍒' },
  { unifiedCode: 'U+1f353', cnCode: '🍓' },
  { unifiedCode: 'U+1f95d', cnCode: '🥝' },
  { unifiedCode: 'U+1f345', cnCode: '🍅' },
  { unifiedCode: 'U+1f951', cnCode: '🥑' },
  { unifiedCode: 'U+1f346', cnCode: '🍆' },
  { unifiedCode: 'U+1f954', cnCode: '🥔' },
  { unifiedCode: 'U+1f955', cnCode: '🥕' },
  { unifiedCode: 'U+1f33d', cnCode: '🌽' },
  { unifiedCode: 'U+1f336', cnCode: '🌶' },
  { unifiedCode: 'U+1f952', cnCode: '🥒' },
  { unifiedCode: 'U+1f344', cnCode: '🍄' },
  { unifiedCode: 'U+1f95c', cnCode: '🥜' },
  { unifiedCode: 'U+1f330', cnCode: '🌰' },
  { unifiedCode: 'U+1f35e', cnCode: '🍞' },
  { unifiedCode: 'U+1f95e', cnCode: '🥞' },
  { unifiedCode: 'U+1f9c0', cnCode: '🧀' },
  { unifiedCode: 'U+1f356', cnCode: '🍖' },
  { unifiedCode: 'U+1f357', cnCode: '🍗' },
  { unifiedCode: 'U+1f953', cnCode: '🥓' },
  { unifiedCode: 'U+1f354', cnCode: '🍔' },
  { unifiedCode: 'U+1f35f', cnCode: '🍟' },
  { unifiedCode: 'U+1f355', cnCode: '🍕' },
  { unifiedCode: 'U+1f32d', cnCode: '🌭' },
  { unifiedCode: 'U+1f32e', cnCode: '🌮' },
  { unifiedCode: 'U+1f32f', cnCode: '🌯' },
  { unifiedCode: 'U+1f959', cnCode: '🥙' },
  { unifiedCode: 'U+1f95a', cnCode: '🥚' },
  { unifiedCode: 'U+1f373', cnCode: '🍳' },
  { unifiedCode: 'U+1f958', cnCode: '🥘' },
  { unifiedCode: 'U+1f372', cnCode: '🍲' },
  { unifiedCode: 'U+1f957', cnCode: '🥗' },
  { unifiedCode: 'U+1f35b', cnCode: '🍛' },
  { unifiedCode: 'U+1f35c', cnCode: '🍜' },
  { unifiedCode: 'U+1f35d', cnCode: '🍝' },
  { unifiedCode: 'U+1f360', cnCode: '🍠' },
  { unifiedCode: 'U+1f36a', cnCode: '🍪' },
  { unifiedCode: 'U+1f382', cnCode: '🎂' },
  { unifiedCode: 'U+1f37c', cnCode: '🍼' },
  { unifiedCode: 'U+1f95b', cnCode: '🥛' },
  { unifiedCode: 'U+1f375', cnCode: '🍵' },
  { unifiedCode: 'U+1f376', cnCode: '🍶' },
  { unifiedCode: 'U+1f37e', cnCode: '🍾' },
  { unifiedCode: 'U+1f377', cnCode: '🍷' },
  { unifiedCode: 'U+1f378', cnCode: '🍸' },
  { unifiedCode: 'U+1f379', cnCode: '🍹' },
  { unifiedCode: 'U+1f37a', cnCode: '🍺' },
  { unifiedCode: 'U+1f37b', cnCode: '🍻' },
  { unifiedCode: 'U+1f942', cnCode: '🥂' },
  { unifiedCode: 'U+1f943', cnCode: '🥃' },
];
// 体育运动
export const sportsEmoji: EmojiconType[] = [
  { unifiedCode: 'U+1f93a', cnCode: '🤺' },
  { unifiedCode: 'U+1f3c7', cnCode: '🏇' },
  { unifiedCode: 'U+26f7', cnCode: '⛷' },
  { unifiedCode: 'U+1f3c2', cnCode: '🏂' },
  { unifiedCode: 'U+1f3cc', cnCode: '🏌' },
  // { unifiedCode: "U+1f3cc U+fe0f U+200d U+2640 U+fe0f", "cnCode": "🏌️‍♀️" },
  { unifiedCode: 'U+1f3c4', cnCode: '🏄' },
  // { unifiedCode: "U+1f3c4 U+200d U+2640 U+fe0f", "cnCode": "🏄‍♀️" },
  // { unifiedCode: "U+1f6a3 U+1f3fb", "cnCode": "🚣🏻" },
  { unifiedCode: 'U+1f3ca', cnCode: '🏊' },
  { unifiedCode: 'U+26f9', cnCode: '⛹' },
  // { unifiedCode: "U+26f9 U+fe0f U+200d U+2640 U+fe0f", "cnCode": "⛹️‍♀️" },
  { unifiedCode: 'U+1f3cb', cnCode: '🏋' },
  { unifiedCode: 'U+1f6b4', cnCode: '🚴' },
  { unifiedCode: 'U+1f6b5', cnCode: '🚵' },
  { unifiedCode: 'U+1f938', cnCode: '🤸' },
  { unifiedCode: 'U+1f93c', cnCode: '🤼' },
  { unifiedCode: 'U+1f93d', cnCode: '🤽' },
  { unifiedCode: 'U+1f93e', cnCode: '🤾' },
  { unifiedCode: 'U+1f939', cnCode: '🤹' },
  { unifiedCode: 'U+26bd', cnCode: '⚽' },
  { unifiedCode: 'U+26be', cnCode: '⚾' },
  { unifiedCode: 'U+1f3c0', cnCode: '🏀' },
  { unifiedCode: 'U+1f3d0', cnCode: '🏐' },
  { unifiedCode: 'U+1f3c8', cnCode: '🏈' },
  { unifiedCode: 'U+1f3c9', cnCode: '🏉' },
  { unifiedCode: 'U+1f3be', cnCode: '🎾' },
  { unifiedCode: 'U+1f3b3', cnCode: '🎳' },
  { unifiedCode: 'U+1f3cf', cnCode: '🏏' },
  { unifiedCode: 'U+1f3d1', cnCode: '🏑' },
  { unifiedCode: 'U+1f3d2', cnCode: '🏒' },
  { unifiedCode: 'U+1f3d3', cnCode: '🏓' },
  { unifiedCode: 'U+1f3f8', cnCode: '🏸' },
  { unifiedCode: 'U+1f94a', cnCode: '🥊' },
  { unifiedCode: 'U+1f94b', cnCode: '🥋' },
  { unifiedCode: 'U+1f945', cnCode: '🥅' },
  { unifiedCode: 'U+26f3', cnCode: '⛳' },
  { unifiedCode: 'U+26f8', cnCode: '⛸' },
  { unifiedCode: 'U+1f3a3', cnCode: '🎣' },
  { unifiedCode: 'U+1f3bf', cnCode: '🎿' },
  { unifiedCode: 'U+1f3af', cnCode: '🎯' },
  { unifiedCode: 'U+1f3b1', cnCode: '🎱' },
  { unifiedCode: 'U+1f3ae', cnCode: '🎮' },
  { unifiedCode: 'U+1f3f9', cnCode: '🏹' },
];

const emojiconsArr: EmojiconsArr[] = [
  {
    emoji: emojicons,
    title: '表情',
  },
  {
    emoji: animalAndNativeEmoji,
    title: '动物与大自然',
  },
  {
    emoji: foodAndDrinkEmoji,
    title: '美食与饮料',
  },
  {
    emoji: sportsEmoji,
    title: '活动',
  },
];
export default emojiconsArr;
